name: Run lighthouse CI When Push

runs:
  uses: 'composite'
  steps:
    - name: Run Lighthouse CI
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      run: |
        npm install -g @lhci/cli
        npm run lgh || echo "Fail to Run Lighthouse CI!"
